Lima

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -32,6 +32,10 @@ build:
           ls -l $WERCKER_CACHE_DIR 
           echo WERCKER_GIT_COMMIT=$WERCKER_GIT_COMMIT   
           echo WERCKER_GIT_REPOSITORY=$WERCKER_GIT_REPOSITORY       
+    - script: 
+        name: Run the unit tests
+        code: |
+          go test ./...
     - script:
         name: Copy contents of repository to /pipeline/output for next pipeline to use
         code: cp -r /pipeline/source/* /pipeline/output
@@ -95,7 +99,7 @@ test-docker-build2:
   # Test that we can pull the newly-created image, start it and connect to it
   box: alpine
   services: 
-    - name: test-container$BUILDID
+    - name: test-docker-build-container
       id: docker.io/$USERNAME/wercker-test:test-docker-build1
       ports:
         - "5000"
@@ -106,7 +110,7 @@ test-docker-build2:
           export BUILDID=`cat /pipeline/cache/build-id`
           echo BUILDID=$BUILDID
     - script:
-        name: Check what we've got # looks like pipeline/output ($WERCKER_OUTPUT_DIR) is not copied to next pipeline, but /pipeline/source ($WERCKER_ROOT) is not
+        name: Check what we've got 
         code: |
           echo Contents of /pipeline
           ls -l /pipeline   
@@ -122,11 +126,79 @@ test-docker-build2:
     - script: 
         name: Wait for container to start 
         code: | 
-          until $(curl --output /dev/null --silent --head --fail http://test-container:5000); do printf '.'; sleep 5; done 
+          until $(curl --output /dev/null --silent --head --fail http://test-docker-build-container:5000); do printf '.'; sleep 5; done 
     - script: 
         name: Test the container
         code: |
             if curlOutput=`curl -s test-container:5000`; then 
+                if [ "$curlOutput" == "Hello World!!" ]; then
+                    echo "Test passed: container gave expected response"
+                else
+                    echo "Test failed: container gave unexpected response: " $curlOutput
+                    exit 1
+                fi   
+            else 
+                echo "Test failed: container did not respond"
+                exit 1
+            fi               
+test-docker-push-classic1:
+  # Test the "classic" docker-push step (which commits the current container) (part 1) 
+  box: google/golang
+  steps:
+    - script:
+        name: Get the a unique id for the run, common to all pipelines in the workflow
+        code: |
+          export BUILDID=`cat /pipeline/cache/build-id`
+          echo BUILDID=$BUILDID
+    - script:
+        name: Check what we've got 
+        code: |
+          echo Contents of /pipeline
+          ls -l /pipeline   
+          echo Contents of WERCKER_ROOT=$WERCKER_ROOT
+          ls -l $WERCKER_ROOT        
+          echo Contents of WERCKER_OUTPUT_DIR=$WERCKER_OUTPUT_DIR
+          ls -l $WERCKER_OUTPUT_DIR
+          echo Contents of WERCKER_CACHE_DIR=$WERCKER_CACHE_DIR
+          ls -l $WERCKER_CACHE_DIR 
+    - script:
+        name: Build the executable. This will be run in a golang base image created by committing the current container, so no need to worry about dependencies
+        code: |
+          go build -o myapp 
+          echo veryfying build
+          pwd
+          ls -l           
+    - internal/docker-push: 
+        username: $USERNAME # Docker Hub username. When using CLI, set using "export X_USERNAME=<username>"  
+        password: $PASSWORD # Docker Hub password. When using CLI, set using "export X_PASSWORD=<password>" 
+        repository: docker.io/$USERNAME/wercker-test
+        tag: test-docker-push-classic1
+test-docker-push-classic2:
+  # Test the "classic" docker-push step (which commits the current container) (part 2) 
+  # Test that we can pull the newly-created image, start it and connect to it
+  box: alpine
+  services: 
+    - name: test-docker-push-classic-container
+      id: docker.io/$USERNAME/wercker-test:test-docker-push-classic1
+      ports:
+        - "5000"
+  steps:
+    - script:
+        name: Get the a unique id for the run, common to all pipelines in the workflow
+        code: |
+          export BUILDID=`cat /pipeline/cache/build-id`
+          echo BUILDID=$BUILDID     
+    - script:
+        name: Install Curl
+        code: apk --no-cache add curl 
+    - script: 
+        name: Wait for container to start 
+        code: | 
+          until $(curl --output /dev/null --silent --head --fail http://test-docker-push-classic-container:5000); do printf '.'; sleep 5; done 
+    - script: 
+        name: Test the container
+        code: |
+            if curlOutput=`curl -s test-docker-push-classic-container:5000`; then 
                 if [ "$curlOutput" == "Hello World!!" ]; then
                     echo "Test passed: container gave expected response"
                 else
